"use client"

import { useMemo, useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { Archive, Bell, Check, CheckCheck, CircleAlert, FileText, Filter, HeartPulse, Info, MoreHorizontal, Sparkles, Trash2, UserRound, X } from "lucide-react"
import { DoctorPage } from "@/components/doctor-portal"

type Category = "All" | "Critical" | "Reports" | "Patients" | "System"
type Notice = { id: number; title: string; detail: string; time: string; category: Exclude<Category, "All">; unread?: boolean; urgent?: boolean; icon: typeof Bell }

const initialNotices: Notice[] = [
  { id: 1, title: "Critical patient alert", detail: "Ramesh Patel's report indicates elevated blood pressure. Review recommended within 30 minutes.", time: "8 min ago", category: "Critical", unread: true, urgent: true, icon: CircleAlert },
  { id: 2, title: "New report ready for review", detail: "Meena Shah's Gujarati consultation summary is ready in your patient queue.", time: "28 min ago", category: "Reports", unread: true, icon: FileText },
  { id: 3, title: "Follow-up reminder", detail: "Arjun Joshi is due for a post-consultation follow-up today.", time: "1 hr ago", category: "Patients", icon: UserRound },
  { id: 4, title: "Weekly care summary available", detail: "Your practice insights for August 3–9 are ready to view.", time: "Yesterday", category: "Reports", icon: Sparkles },
  { id: 5, title: "System maintenance complete", detail: "VaaniDoc processing services are operating normally in your region.", time: "Yesterday", category: "System", icon: HeartPulse },
]

export default function DoctorNotifications() {
  const [notices, setNotices] = useState(initialNotices)
  const [filter, setFilter] = useState<Category>("All")
  const unread = notices.filter((notice) => notice.unread).length
  const visible = useMemo(() => filter === "All" ? notices : notices.filter((notice) => notice.category === filter), [filter, notices])
  const markAllRead = () => setNotices((items) => items.map((item) => ({ ...item, unread: false })))
  const dismiss = (id: number) => setNotices((items) => items.filter((item) => item.id !== id))

  return <DoctorPage><div className="flex flex-col gap-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#0d8f88]">Wednesday, August 13, 2026 · 9:42 AM</p><h1 className="mt-2 font-serif text-3xl font-bold tracking-tight text-[#1d3445] md:text-4xl">Notifications</h1><p className="mt-2 text-[#718391]">Stay on top of patient care and practice activity.</p></div><button onClick={markAllRead} className="flex items-center justify-center gap-2 rounded-xl border border-[#dce7ea] bg-white px-4 py-3 text-sm font-bold text-[#1d3445] shadow-sm transition hover:border-[#0d8f88] hover:text-[#0d7771]"><CheckCheck size={17} /> Mark all as read</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Unread" value={unread} tone="teal" icon={Bell} /><Metric label="Critical attention" value={notices.filter((n) => n.urgent).length} tone="coral" icon={CircleAlert} /><Metric label="This week" value={notices.length} tone="blue" icon={Info} /></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
      <section className="overflow-hidden rounded-2xl border border-[#e5edf0] bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-[#edf2f4] px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-serif text-xl font-bold">Activity feed</h2><p className="mt-1 text-sm text-[#718391]">{unread} unread updates need your attention</p></div><div className="flex items-center gap-2 overflow-x-auto pb-1"><Filter size={16} className="shrink-0 text-[#8ba0aa]" />{(["All", "Critical", "Reports", "Patients", "System"] as Category[]).map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold transition ${filter === item ? "bg-[#eaf6f5] text-[#0d7771]" : "text-[#718391] hover:bg-[#f5f8f9]"}`}>{item}</button>)}</div></div><div className="divide-y divide-[#edf2f4]"><AnimatePresence initial={false}>{visible.map((notice) => { const Icon = notice.icon; return <motion.article key={notice.id} layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, height: 0, padding: 0 }} className={`flex gap-4 px-5 py-5 ${notice.unread ? "bg-[#fbfefe]" : ""}`}><span className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${notice.urgent ? "bg-[#fff0ed] text-[#e86f5a]" : "bg-[#eaf6f5] text-[#0d8f88]"}`}><Icon size={18} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div className="flex items-center gap-2"><h3 className="text-sm font-bold text-[#1d3445]">{notice.title}</h3>{notice.unread && <span className="size-2 rounded-full bg-[#0d8f88]" aria-label="Unread" />}</div><span className="text-xs text-[#91a1aa]">{notice.time}</span></div><p className="mt-1 text-sm leading-6 text-[#718391]">{notice.detail}</p><div className="mt-3 flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${notice.urgent ? "bg-[#fff0ed] text-[#d86150]" : "bg-[#f1f6f7] text-[#6b8190]"}`}>{notice.category}</span>{notice.unread && <button onClick={() => setNotices((items) => items.map((item) => item.id === notice.id ? { ...item, unread: false } : item))} className="text-xs font-bold text-[#0d8f88] hover:underline">Mark read</button>}<button onClick={() => dismiss(notice.id)} className="ml-auto text-[#9aaab3] transition hover:text-[#d86150]" aria-label={`Archive ${notice.title}`}><Archive size={15} /></button></div></div></motion.article>})}</AnimatePresence>{visible.length === 0 && <div className="px-5 py-12 text-center text-sm text-[#718391]">No notifications in this category.</div>}</div></section>
      <aside className="flex flex-col gap-6"><div className="rounded-2xl bg-[#12304a] p-6 text-white shadow-lg shadow-[#12304a]/10"><div className="flex items-center gap-2 text-[#8ee0d7]"><Sparkles size={17} /><span className="text-xs font-bold uppercase tracking-[.16em]">AI briefing</span></div><h2 className="mt-5 font-serif text-2xl font-bold leading-tight">Your attention is best spent on Ramesh today.</h2><p className="mt-3 text-sm leading-6 text-[#c9dce5]">One critical alert is waiting. Reports are flowing normally, and all system services are healthy.</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#18a7a0] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#22b6ae]">Open patient queue <MoreHorizontal size={16} /></button></div><div className="rounded-2xl border border-[#e5edf0] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-serif text-lg font-bold">Notification settings</h2><Bell size={18} className="text-[#0d8f88]" /></div><p className="mt-2 text-sm leading-6 text-[#718391]">Choose what reaches you while you are caring for patients.</p><button className="mt-4 text-sm font-bold text-[#0d8f88] hover:underline">Manage preferences</button></div></aside>
    </div></div></DoctorPage>
}
function Metric({ label, value, tone, icon: Icon }: { label: string; value: number; tone: "teal" | "coral" | "blue"; icon: typeof Bell }) { const styles = { teal: "bg-[#eaf6f5] text-[#0d8f88]", coral: "bg-[#fff0ed] text-[#e86f5a]", blue: "bg-[#eaf5fb] text-[#1769aa]" }; return <div className="rounded-2xl border border-[#e5edf0] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className={`flex size-10 items-center justify-center rounded-xl ${styles[tone]}`}><Icon size={18} /></span><span className="text-xs font-bold text-[#91a1aa]">TODAY</span></div><p className="mt-5 text-sm text-[#718391]">{label}</p><p className="mt-1 text-3xl font-bold text-[#1d3445]">{value}</p></div> }
