"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, Clock3, Filter, Search, ShieldCheck, Video } from "lucide-react"
import { DoctorShell, DoctorPage } from "@/components/doctor-portal"

const patients = [
  ["Ramesh Patel", "VD-20847", "Headache, fatigue", "Medium", "6 min ago"],
  ["Meera Shah", "VD-20846", "Cough, sore throat", "Low", "18 min ago"],
  ["Arjun Desai", "VD-20845", "Chest discomfort", "High", "32 min ago"],
  ["Kiran Joshi", "VD-20844", "Joint pain", "Low", "44 min ago"],
]

export default function ConsultationsPage() {
  const [query, setQuery] = useState("")
  const [filter, setFilter] = useState("All")
  const [notice, setNotice] = useState("")
  const visible = useMemo(() => patients.filter(([name, id, symptom, risk]) => (filter === "All" || risk === filter) && `${name} ${id} ${symptom}`.toLowerCase().includes(query.toLowerCase())), [filter, query])
  return <DoctorPage><div className="flex flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="eyebrow">CLINICAL WORKSPACE</p><h1 className="mt-2 font-serif text-3xl font-bold">Consultations</h1><p className="mt-2 text-[#718391]">Review AI-prepared patient summaries and make faster care decisions.</p></div><button onClick={() => setNotice("New consultation started") } className="teal-button"><Video size={16} /> Start consultation</button></div>
    {notice && <div className="rounded-xl border border-[#bfe7df] bg-[#effaf7] px-4 py-3 text-sm font-semibold text-[#0d8f88]">{notice}</div>}
    <div className="grid gap-4 md:grid-cols-4">{([ ["18", "Open summaries", Activity, "+4 today"], ["07", "Priority attention", AlertTriangle, "2 high risk"], ["92%", "AI accuracy", ShieldCheck, "+2.4%"], ["14 min", "Avg. review time", Clock3, "-18% this week"] ] as any[]).map(([value, label, Icon, note]) => <div key={String(label)} className="portal-card p-5"><div className="flex items-start justify-between"><div><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-sm text-[#718391]">{label}</p></div><span className="flex size-9 items-center justify-center rounded-xl bg-[#e7f6f3] text-[#0d8f88]"><Icon size={18} /></span></div><p className="mt-4 text-xs font-semibold text-[#0d8f88]">{note}</p></div>)}</div>
    <div className="flex flex-col gap-3 rounded-2xl border border-[#dce7eb] bg-white p-4 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-[#dce7eb] bg-[#f7fafb] px-3 py-2"><Search size={17} className="text-[#93a3ad]" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search patients, IDs, or symptoms" className="w-full bg-transparent text-sm outline-none" /></div><div className="flex items-center gap-2"><Filter size={16} className="text-[#718391]" />{["All", "High", "Medium", "Low"].map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-bold ${filter === item ? "bg-[#0d8f88] text-white" : "bg-[#f3f7f8] text-[#718391]"}`}>{item}</button>)}</div></div>
    <section className="portal-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e5edf0] px-5 py-4"><div><h2 className="font-semibold">Review queue</h2><p className="mt-1 text-xs text-[#718391]">AI summaries waiting for clinical review</p></div><span className="rounded-full bg-[#e7f6f3] px-3 py-1 text-xs font-bold text-[#0d8f88]">{visible.length} visible</span></div><div className="divide-y divide-[#e8eef0]">{visible.map(([name, id, symptom, risk, time]) => <div key={id} className="flex flex-col gap-4 px-5 py-5 md:flex-row md:items-center"><div className="flex flex-1 items-center gap-4"><span className="flex size-11 items-center justify-center rounded-full bg-[#e0f2f0] font-bold text-[#0d8f88]">{name.split(" ").map(x => x[0]).join("")}</span><div><div className="flex items-center gap-2"><h3 className="font-semibold">{name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${risk === "High" ? "bg-[#fee4e2] text-[#c2413d]" : risk === "Medium" ? "bg-[#fff1d6] text-[#a46716]" : "bg-[#e1f4ef] text-[#0d8f88]"}`}>{risk} risk</span></div><p className="mt-1 text-xs text-[#718391]">{id} · Gujarat · Gujarati</p><p className="mt-2 text-sm text-[#526675]">{symptom}</p></div></div><div className="flex items-center justify-end gap-4"><div className="text-right"><p className="text-xs font-semibold text-[#526675]">Needs review</p><p className="mt-1 text-xs text-[#9aa9b2]">{time}</p></div><Link href={`/doctor/patient/${id}`} className="rounded-lg border border-[#dce7eb] p-2 text-[#718391] hover:border-[#0d8f88] hover:text-[#0d8f88]"><ArrowRight size={16} /></Link></div></div>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-2"><div className="portal-card p-5"><h2 className="font-semibold">Today&apos;s activity</h2><div className="mt-5 flex flex-col gap-4">{[["09:42", "Reviewed Ramesh Patel"], ["09:18", "Consultation completed"], ["08:55", "New priority alert"]].map(([time, title], i) => <div key={title} className="flex gap-3"><span className="flex size-7 items-center justify-center rounded-full bg-[#f0f6f6] text-[#0d8f88]">{i === 0 ? <CheckCircle2 size={14} /> : <Clock3 size={14} />}</span><p className="text-sm font-semibold">{title}<span className="ml-2 text-xs font-normal text-[#718391]">{time}</span></p></div>)}</div></div><div className="rounded-2xl bg-[#e6f6f3] p-5"><div className="flex size-10 items-center justify-center rounded-xl bg-white text-[#0d8f88]"><ShieldCheck size={20} /></div><h3 className="mt-4 font-semibold">AI clinical assistant</h3><p className="mt-2 text-sm leading-6 text-[#52716e]">Translate notes, compare symptoms, and prepare a differential summary.</p></div></div>
  </div></DoctorPage>
}
