'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, FileText, Globe2, HeartPulse, Languages, LockKeyhole, Menu, Mic, Play, ShieldCheck, Sparkles, Stethoscope, X } from 'lucide-react'

const languages = ['हिंदी', 'मराठी', 'বাংলা', 'தமிழ்', 'తెలుగు', 'ಕನ್ನಡ', 'ગુજરાતી', 'ਪੰਜਾਬੀ', 'മലയാളം']
const stats = [['12+', 'languages supported'], ['60%', 'less documentation time'], ['50K+', 'patient interactions'], ['98%', 'clinician satisfaction']]
const features = [
  { icon: Languages, title: 'Multilingual by default', text: 'Speak naturally in your language. VaaniDoc understands patients exactly as they are.', tone: 'teal' },
  { icon: Mic, title: 'Voice-first workflow', text: 'Capture conversations hands-free and turn them into structured clinical notes.', tone: 'blue' },
  { icon: FileText, title: 'Instant documentation', text: 'Get clean, complete notes in seconds — so you can focus on care, not paperwork.', tone: 'orange' },
  { icon: ShieldCheck, title: 'Privacy you can trust', text: 'Built with healthcare-grade security. Your patient data stays protected.', tone: 'navy' },
]

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [demoOpen, setDemoOpen] = useState(false)
  return (
    <main>
      <nav className="sticky top-0 z-50 border-b border-[#dfeaf0]/80 bg-white/90 backdrop-blur-xl">
        <div className="container flex h-[72px] items-center justify-between">
          <a href="#top" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#1769aa] text-white"><HeartPulse size={20} /></span><span className="font-display text-[20px] font-bold tracking-[-.04em] text-[#12304a]">Vaani<span className="text-[#18a7a0]">Doc</span></span></a>
          <div className="hidden items-center gap-8 md:flex"><a className="nav-link" href="#how">How it works</a><a className="nav-link" href="#features">Features</a><a className="nav-link" href="#impact">Impact</a><a className="nav-link" href="#about">About us</a></div>
          <div className="hidden items-center gap-3 md:flex"><button className="btn-secondary">Log in</button><button className="btn-primary">Get started <ArrowRight size={16} /></button></div>
          <button aria-label="Toggle menu" className="grid size-10 place-items-center rounded-lg border border-[#d9e7ee] md:hidden" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {mobileOpen && <div className="container flex flex-col gap-5 border-t border-[#d9e7ee] py-5 md:hidden"><a className="nav-link" href="#how">How it works</a><a className="nav-link" href="#features">Features</a><a className="nav-link" href="#impact">Impact</a><button className="btn-primary w-full">Get started <ArrowRight size={16} /></button></div>}
      </nav>

      <section id="top" className="overflow-hidden border-b border-[#d9e7ee] bg-[#f7fbfd]">
        <div className="container grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-20">
          <div className="reveal max-w-[590px]"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#bfe5e5] bg-[#eefafa] px-3 py-1.5 text-xs font-bold text-[#168c8b]"><Sparkles size={14} /> AI-powered healthcare, in every language</div><h1 className="font-display text-balance text-[clamp(42px,6vw,73px)] font-bold leading-[1.04] tracking-[-.065em] text-[#12304a]">Healthcare that <span className="text-[#1769aa]">speaks your language.</span></h1><p className="mt-6 max-w-[510px] text-pretty text-[17px] leading-7 text-[#647d8c]">VaaniDoc helps healthcare workers understand patients better and document care faster — across every voice, every language, every village.</p><div className="mt-9 flex flex-wrap gap-3"><button className="btn-primary">Start a free pilot <ArrowRight size={17} /></button><button className="btn-secondary" onClick={() => setDemoOpen(true)}><Play size={16} fill="currentColor" /> See how it works</button></div><div className="mt-7 flex items-center gap-3 text-xs font-semibold text-[#76909d]"><span className="flex -space-x-2">{['R','A','S'].map((x, i) => <span key={x} className={`grid size-7 place-items-center rounded-full border-2 border-[#f7fbfd] text-[10px] text-white ${['bg-[#1769aa]','bg-[#18a7a0]','bg-[#12304a]'][i]}`}>{x}</span>)}</span><span>Trusted by 50,000+ healthcare workers</span></div></div>
          <div className="relative min-h-[420px] lg:min-h-[500px]"><div className="hero-blob absolute right-[-10%] top-[4%] h-[420px] w-[98%] rotate-[-8deg] lg:h-[500px]" /><div className="float-card absolute left-[2%] top-[6%] z-10 w-[92%] rounded-2xl border border-[#d6e6ed] bg-white p-5 shadow-[0_24px_70px_rgba(18,48,74,.12)] lg:left-[5%] lg:w-[79%]"><div className="flex items-center justify-between border-b border-[#e6eff3] pb-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#eaf5fb] text-[#1769aa]"><Stethoscope size={18} /></span><div><p className="text-sm font-bold text-[#12304a]">New patient intake</p><p className="text-[11px] text-[#8aa0ab]">Today, 10:42 AM</p></div></div><span className="rounded-full bg-[#eaf8f6] px-2 py-1 text-[10px] font-bold text-[#149795]">Processing</span></div><div className="mt-5 rounded-xl bg-[#f4f9fb] p-4"><div className="mb-3 flex items-center justify-between text-[11px] font-bold text-[#77909d]"><span>Patient speaking in Hindi</span><span className="flex items-center gap-1 text-[#18a7a0]"><span className="size-1.5 animate-pulse rounded-full bg-[#18a7a0]" /> Listening</span></div><div className="flex h-12 items-center gap-1"><span className="h-4 w-1 rounded-full bg-[#8dd9d2]" /><span className="h-7 w-1 rounded-full bg-[#18a7a0]" /><span className="h-11 w-1 rounded-full bg-[#1769aa]" /><span className="h-6 w-1 rounded-full bg-[#8dd9d2]" /><span className="h-9 w-1 rounded-full bg-[#18a7a0]" /><span className="h-3 w-1 rounded-full bg-[#8dd9d2]" /><span className="h-8 w-1 rounded-full bg-[#1769aa]" /><span className="h-5 w-1 rounded-full bg-[#8dd9d2]" /><span className="h-10 w-1 rounded-full bg-[#18a7a0]" /><span className="h-6 w-1 rounded-full bg-[#1769aa]" /><span className="h-3 w-1 rounded-full bg-[#8dd9d2]" /></div></div><div className="mt-5"><div className="mb-3 flex items-center gap-2 text-xs font-bold text-[#718a98]"><Globe2 size={14} className="text-[#1769aa]" /> Translating to English</div><div className="rounded-lg border border-[#dfecef] bg-white p-3 text-sm leading-6 text-[#456272]">Patient reports fever and body ache for the past two days. No history of cough or breathlessness.</div></div></div><div className="float-card-delay absolute bottom-[8%] right-[-2%] z-20 w-[61%] rounded-2xl border border-[#d6e6ed] bg-white p-4 shadow-[0_18px_50px_rgba(18,48,74,.14)] lg:right-[0%]"><div className="flex items-center gap-2 text-xs font-bold text-[#12304a]"><span className="grid size-7 place-items-center rounded-md bg-[#eaf8f6] text-[#18a7a0]"><Check size={15} /></span> Clinical note ready</div><div className="mt-3 h-2 w-[90%] rounded-full bg-[#dcecf1]" /><div className="mt-2 h-2 w-[70%] rounded-full bg-[#e8f1f4]" /><div className="mt-2 h-2 w-[82%] rounded-full bg-[#e8f1f4]" /><button className="mt-4 w-full rounded-lg bg-[#1769aa] py-2 text-[11px] font-bold text-white">Review note</button></div></div>
        </div>
      </section>

      <section className="border-b border-[#d9e7ee] bg-white"><div className="container grid grid-cols-2 divide-x divide-[#d9e7ee] py-8 md:grid-cols-4">{stats.map(([value, label]) => <div key={label} className="px-4 text-center first:pl-0 last:pr-0"><p className="font-display text-3xl font-bold tracking-[-.05em] text-[#12304a] md:text-4xl">{value}</p><p className="mt-1 text-xs font-semibold text-[#8196a1]">{label}</p></div>)}</div></section>

      <section id="how" className="container py-24"><div className="max-w-[580px]"><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#18a7a0]">Simple by design</p><h2 className="font-display text-balance text-4xl font-bold tracking-[-.05em] text-[#12304a] md:text-5xl">Better conversations. Better care.</h2><p className="mt-5 text-[16px] leading-7 text-[#718994]">From the first hello to the final note, VaaniDoc fits naturally into the way healthcare already happens.</p></div><div className="mt-14 grid gap-10 md:grid-cols-3">{[['01','Listen','Talk to your patient naturally in the language they are most comfortable with.'],['02','Understand','VaaniDoc translates, summarizes, and organizes the conversation in real time.'],['03','Care','Review a complete clinical note and spend more time where it matters — with your patient.']].map(([num,title,text], i) => <div key={title} className="relative border-t-2 border-[#dceaf0] pt-7"><span className="font-display text-5xl font-bold text-[#b7dce4]">{num}</span><h3 className="mt-5 font-display text-xl font-bold text-[#12304a]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#718994]">{text}</p>{i < 2 && <ArrowRight className="absolute right-2 top-9 hidden text-[#b7dce4] md:block" size={22} />}</div>)}</div></section>

      <section id="features" className="bg-[#eaf5fb] py-24"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#1769aa]">Everything you need</p><h2 className="font-display text-4xl font-bold tracking-[-.05em] text-[#12304a] md:text-5xl">Built for the real world.</h2></div><p className="max-w-[330px] text-sm leading-6 text-[#6e8794]">Thoughtful tools for the people doing the most important work.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{features.map(({icon: Icon, title, text, tone}) => <article key={title} className="rounded-2xl border border-[#d4e6ed] bg-white p-7 transition-transform hover:-translate-y-1"><span className={`grid size-11 place-items-center rounded-xl ${tone === 'teal' ? 'bg-[#e9f8f6] text-[#18a7a0]' : tone === 'blue' ? 'bg-[#eaf5fb] text-[#1769aa]' : tone === 'orange' ? 'bg-[#fff4e9] text-[#c8752c]' : 'bg-[#e9eef3] text-[#12304a]'}`}><Icon size={21} /></span><h3 className="mt-6 font-display text-xl font-bold text-[#12304a]">{title}</h3><p className="mt-3 max-w-[420px] text-sm leading-6 text-[#718994]">{text}</p><a href="#top" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#1769aa]">Learn more <ArrowRight size={15} /></a></article>)}</div></div></section>

      <section id="impact" className="container py-24"><div className="grid items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#18a7a0]">Made for India</p><h2 className="font-display text-balance text-4xl font-bold tracking-[-.05em] text-[#12304a] md:text-5xl">One platform. Every language.</h2><p className="mt-5 text-[16px] leading-7 text-[#718994]">India speaks hundreds of languages. Healthcare should too. VaaniDoc is built from the ground up to make quality care more inclusive and accessible.</p><div className="mt-8 flex flex-wrap gap-2">{languages.map(language => <span key={language} className="rounded-full border border-[#cfe2e9] bg-white px-3 py-2 text-sm font-semibold text-[#456575]">{language}</span>)}</div></div><div className="grid-paper relative min-h-[330px] overflow-hidden rounded-3xl border border-[#d5e6ed] bg-[#f4fbfc] p-8"><div className="absolute right-8 top-8 rounded-xl border border-[#cfe6e6] bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#8499a4]">Language coverage</p><p className="mt-1 font-display text-3xl font-bold text-[#12304a]">12+</p><p className="text-xs text-[#18a7a0]">and growing</p></div><div className="absolute bottom-8 left-8 max-w-[220px]"><div className="mb-3 flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-[#1769aa] text-white"><Globe2 size={15} /></span><span className="text-sm font-bold text-[#12304a]">Care without barriers</span></div><p className="text-xs leading-5 text-[#718994]">Every patient deserves to be heard, understood, and cared for.</p></div><div className="absolute left-[38%] top-[31%] grid size-28 place-items-center rounded-full border-8 border-white bg-[#bde8e3] text-[#1769aa] shadow-[0_12px_30px_rgba(23,105,170,.15)]"><Languages size={43} /></div></div></div></section>

      <section id="about" className="bg-[#12304a] py-24 text-white"><div className="container grid items-center gap-12 lg:grid-cols-[1fr_.85fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#7ed6cf]">Your data, protected</p><h2 className="font-display text-balance text-4xl font-bold tracking-[-.05em] md:text-5xl">Trust is not a feature.<br />It&apos;s the foundation.</h2><p className="mt-5 max-w-[520px] text-[16px] leading-7 text-[#b3c9d3]">VaaniDoc is designed with privacy at its core. Secure by default, transparent by design, and built to meet the highest standards of healthcare data protection.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="flex items-center gap-3"><LockKeyhole className="text-[#7ed6cf]" size={20} /><span className="text-sm font-semibold">End-to-end encryption</span></div><div className="flex items-center gap-3"><ShieldCheck className="text-[#7ed6cf]" size={20} /><span className="text-sm font-semibold">HIPAA-ready infrastructure</span></div><div className="flex items-center gap-3"><Check className="text-[#7ed6cf]" size={20} /><span className="text-sm font-semibold">Your data stays yours</span></div><div className="flex items-center gap-3"><HeartPulse className="text-[#7ed6cf]" size={20} /><span className="text-sm font-semibold">Built with clinicians</span></div></div></div><div className="rounded-2xl border border-[#36566a] bg-[#173a55] p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#245b70] text-[#7ed6cf]"><LockKeyhole size={20} /></span><div><p className="text-sm font-bold">Privacy dashboard</p><p className="text-xs text-[#9fbac5]">Your security at a glance</p></div></div><div className="mt-7 flex flex-col gap-3">{['Data encrypted at rest','Access controls enabled','Audit logs active','Consent management ready'].map(item => <div key={item} className="flex items-center justify-between rounded-lg bg-[#21445e] px-4 py-3 text-sm"><span className="text-[#c8dbe2]">{item}</span><span className="grid size-5 place-items-center rounded-full bg-[#7ed6cf] text-[#12304a]"><Check size={13} /></span></div>)}</div></div></div></section>

      <section className="container py-24 text-center"><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#18a7a0]">Start a conversation</p><h2 className="mx-auto max-w-[670px] font-display text-balance text-4xl font-bold tracking-[-.06em] text-[#12304a] md:text-6xl">The future of healthcare speaks <span className="text-[#1769aa]">every language.</span></h2><p className="mx-auto mt-5 max-w-[520px] text-[16px] leading-7 text-[#718994]">See how VaaniDoc can help your team deliver better care, with less paperwork.</p><button className="btn-primary mt-8">Book a demo <ArrowRight size={17} /></button></section>

      <footer className="border-t border-[#d9e7ee] bg-white"><div className="container flex flex-col gap-8 py-10 md:flex-row md:items-center md:justify-between"><div><a href="#top" className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#1769aa] text-white"><HeartPulse size={17} /></span><span className="font-display text-lg font-bold tracking-[-.04em] text-[#12304a]">Vaani<span className="text-[#18a7a0]">Doc</span></span></a><p className="mt-3 text-xs text-[#8097a3]">Healthcare that speaks your language.</p></div><div className="flex flex-wrap gap-6 text-xs font-semibold text-[#6e8794]"><a href="#features">Features</a><a href="#impact">Languages</a><a href="#about">Privacy</a><a href="#top">Contact</a></div><p className="text-xs text-[#a1b2ba]">© 2024 VaaniDoc. Built for better care.</p></div></footer>

      {demoOpen && <div className="fixed inset-0 z-[60] grid place-items-center bg-[#12304a]/50 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-bold text-[#12304a]">See VaaniDoc in action</h2><button aria-label="Close demo" onClick={() => setDemoOpen(false)} className="grid size-9 place-items-center rounded-lg border border-[#d9e7ee]"><X size={18} /></button></div><div className="mt-6 grid aspect-video place-items-center rounded-xl bg-[#eaf5fb]"><button className="grid size-14 place-items-center rounded-full bg-[#1769aa] text-white shadow-lg"><Play size={24} fill="currentColor" /></button></div><p className="mt-5 text-sm leading-6 text-[#718994]">Watch how a patient conversation becomes a clear clinical note in seconds.</p></div></div>}
    </main>
  )
}
