"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { Bell, BarChart3, ChevronDown, ClipboardCheck, LayoutDashboard, Menu, Search, Settings, Users, X } from "lucide-react"
import { useState } from "react"

const navigation = [
  { href: "/doctor/dashboard", label: "Overview", description: "Doctor dashboard overview", icon: LayoutDashboard },
  { href: "/doctor/patients", label: "Patient Queue", description: "Incoming AI-generated reports", icon: Users },
  { href: "/doctor/consultations", label: "Active Consultations", description: "Patients currently under care", icon: ClipboardCheck, badge: "8 Active" },
  { href: "/doctor/analytics", label: "Analytics & AI Insights", description: "Performance and clinical metrics", icon: BarChart3, badge: "AI" },
  { href: "/doctor/notifications", label: "Notifications", description: "Alerts and care updates", icon: Bell, badge: "3" },
  { href: "/doctor/settings", label: "Settings", description: "Profile and preferences", icon: Settings },
]

export function DoctorShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-[#f8fafb] text-[#1d3445]"><header className="border-b border-[#e5edf0] bg-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-[#68808f] lg:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={20} /> : <Menu size={20} />}</button><Link href="/" className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#0d8f88] text-sm font-bold text-white shadow-sm">V</span><span className="font-serif text-xl font-bold">VaaniDoc <span className="font-sans text-xs font-medium text-[#7a8c98]">Clinician</span></span></Link></div><div className="hidden items-center gap-3 md:flex"><Link href="/doctor/notifications" className="relative rounded-lg p-2 text-[#708592]" aria-label="Notifications"><Bell size={19} /><span className="absolute right-1 top-1 size-2 rounded-full bg-[#ef765d]" /></Link><div className="flex items-center gap-3 border-l border-[#e5edf0] pl-4"><span className="flex size-9 items-center justify-center rounded-full bg-[#dceeed] text-sm font-bold text-[#0d7771]">DP</span><div><p className="text-sm font-semibold">Dr. Priya Patel</p><p className="text-xs text-[#7a8c98]">General Physician</p></div><ChevronDown size={15} className="text-[#91a1aa]" /></div></div></div></header><div className="mx-auto flex max-w-[1440px]"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 top-[69px] z-20 w-72 border-r border-[#e5edf0] bg-white p-4 shadow-xl transition-transform lg:static lg:translate-x-0 lg:shadow-none`}><div className="mb-5 px-3"><p className="text-[10px] font-bold tracking-[0.18em] text-[#9aabb4]">CLINICIAN WORKSPACE</p><p className="mt-1 text-xs text-[#718391]">Care coordination at a glance</p></div><nav className="flex flex-col gap-1.5">{navigation.map(item => <NavItem key={item.href} {...item} />)}</nav><div className="mt-8 rounded-2xl bg-[#0d7771] p-4 text-white shadow-lg shadow-[#0d7771]/15"><p className="text-[10px] font-bold tracking-[0.2em] text-[#a8e4dc]">VAANIDOC AI</p><p className="mt-2 font-serif text-lg font-bold">Multilingual Healthcare Intelligence</p><ul className="mt-4 flex flex-col gap-2 text-xs text-[#d5f5f0]"><li>✓ 22+ Languages</li><li>✓ AI Symptom Detection</li><li>✓ Privacy First</li><li>✓ Rural Connectivity Optimized</li></ul></div></aside><main className="min-w-0 flex-1">{children}</main></div></div>
}

function NavItem({ href, label, description, icon: Icon, badge }: { href: string; label: string; description: string; icon: typeof LayoutDashboard; badge?: string }) { const pathname = usePathname(); const active = pathname === href || (href.includes("patient") && pathname.startsWith("/doctor/patient")); return <Link href={href} className={`group relative flex items-start gap-3 rounded-xl px-3 py-3 transition-all duration-200 ${active ? "bg-[#e8f6f5] text-[#0d7771] shadow-sm" : "text-[#718391] hover:bg-[#f3f8f8] hover:text-[#0d7771]"}`}><span className={`mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg ${active ? "bg-[#0d8f88] text-white" : "bg-[#f4f8f9] text-[#78909d] group-hover:bg-[#e5f4f2] group-hover:text-[#0d7771]"}`}><Icon size={17} /></span><span className="min-w-0 flex-1"><span className={`block text-sm ${active ? "font-bold" : "font-semibold"}`}>{label}</span><span className="mt-0.5 block truncate text-[10px] text-[#91a1aa]">{description}</span></span>{badge && <span className={`mt-1 rounded-full px-2 py-0.5 text-[10px] font-bold ${active ? "bg-white text-[#0d7771]" : "bg-[#e7f6f3] text-[#0d8f88]"}`}>{badge}</span>}{active && <span className="absolute bottom-2 left-0 top-2 w-1 rounded-r-full bg-[#0d8f88]" />}</Link> }

export function DoctorPage({ children }: { children: React.ReactNode }) { return <DoctorShell><div className="mx-auto max-w-[1180px] px-5 py-8 lg:px-10 lg:py-10">{children}</div></DoctorShell> }
export function SearchBar() { return <div className="flex items-center gap-3 rounded-xl border border-[#dce7ea] bg-white px-4 py-3 shadow-sm"><Search size={18} className="text-[#8ba0aa]" /><input className="w-full bg-transparent text-sm outline-none placeholder:text-[#9aaab3]" placeholder="Search patients by name or ID..." aria-label="Search patients" /></div> }
