"use client"

import Link from "next/link"
import { useState } from "react"
import { Bell, ChevronDown, FileText, LayoutDashboard, Menu, Search, Settings, Users, X } from "lucide-react"

export function DoctorShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-[#f8fafb] text-[#1d3445]"><header className="border-b border-[#e5edf0] bg-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-[#68808f] lg:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={20} /> : <Menu size={20} />}</button><Link href="/" className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#0d8f88] text-sm font-bold text-white">V</span><span className="font-serif text-xl font-bold">VaaniDoc <span className="font-sans text-xs font-medium text-[#7a8c98]">Clinician</span></span></Link></div><div className="hidden items-center gap-3 md:flex"><button className="relative rounded-lg p-2 text-[#708592]" aria-label="Notifications"><Bell size={19} /><span className="absolute right-1 top-1 size-2 rounded-full bg-[#ef765d]" /></button><div className="flex items-center gap-3 border-l border-[#e5edf0] pl-4"><span className="flex size-9 items-center justify-center rounded-full bg-[#dceeed] text-sm font-bold text-[#0d7771]">DP</span><div><p className="text-sm font-semibold">Dr. Priya Patel</p><p className="text-xs text-[#7a8c98]">General Physician</p></div><ChevronDown size={15} className="text-[#91a1aa]" /></div></div></div></header><div className="mx-auto flex max-w-[1440px]"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 top-[69px] z-20 w-64 border-r border-[#e5edf0] bg-white p-4 transition-transform lg:static lg:translate-x-0`}><nav className="flex flex-col gap-2"><NavItem href="/doctor/dashboard" icon={<LayoutDashboard size={17} />} label="Overview" /><NavItem href="/doctor/patient/VD-20847" icon={<Users size={17} />} label="Patient queue" /><NavItem href="/patient/report" icon={<FileText size={17} />} label="Sample report" /><NavItem href="/doctor/notifications" icon={<Bell size={17} />} label="Notifications" /><NavItem href="/doctor/settings" icon={<Settings size={17} />} label="Settings" /></nav><div className="mt-12 rounded-2xl bg-[#eaf6f5] p-4"><p className="text-xs font-bold uppercase tracking-widest text-[#0d7771]">VaaniDoc Pro</p><p className="mt-2 text-sm leading-5 text-[#53727b]">Your care team workspace is secured and encrypted.</p></div></aside><main className="min-w-0 flex-1">{children}</main></div></div>
}

function NavItem({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#718391] transition hover:bg-[#f3f8f8] hover:text-[#0d7771]"><span>{icon}</span>{label}</Link> }

export function DoctorPage({ children }: { children: React.ReactNode }) { return <DoctorShell><div className="mx-auto max-w-[1180px] px-5 py-8 lg:px-10 lg:py-10">{children}</div></DoctorShell> }

export function SearchBar() { return <div className="flex items-center gap-3 rounded-xl border border-[#dce7ea] bg-white px-4 py-3 shadow-sm"><Search size={18} className="text-[#8ba0aa]" /><input className="w-full bg-transparent text-sm outline-none placeholder:text-[#9aaab3]" placeholder="Search patients by name or ID..." aria-label="Search patients" /></div> }
