import Link from "next/link"
import { ArrowRight, CalendarDays, ChevronRight, Clock3, FileText, Plus, Stethoscope } from "lucide-react"
import { PageContainer, PatientShell, PortalCard, SectionHeading } from "@/components/patient-portal"

export default function DashboardPage() {
  return <PatientShell><PageContainer>
    <SectionHeading eyebrow="Patient dashboard" title="Good morning, Ananya" description="Take a moment to check in with your health. VaaniDoc is here to help you prepare for your next conversation with a clinician." />
    <div className="grid gap-5 lg:grid-cols-[1.4fr_0.8fr]">
      <PortalCard className="overflow-hidden bg-[#e5f5f3] p-7 sm:p-9"><div className="max-w-xl"><span className="rounded-full bg-white/75 px-3 py-1 text-xs font-bold uppercase tracking-[0.12em] text-[#0d8f88]">New check-in</span><h2 className="mt-5 font-serif text-3xl font-bold tracking-tight sm:text-4xl">How are you feeling today?</h2><p className="mt-3 max-w-lg leading-6 text-[#526675]">Share what you&apos;re experiencing in your own words. It takes about 3 minutes and helps your clinician understand you better.</p><Link href="/patient/intake" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-[#0d8f88] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#0d8f88]/20 transition hover:bg-[#087b75]">Start a check-in <ArrowRight size={16} /></Link></div></PortalCard>
      <PortalCard className="p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#718391]">Next appointment</p><p className="mt-1 font-serif text-2xl font-bold">Dr. Meera Shah</p></div><span className="flex size-11 items-center justify-center rounded-xl bg-[#f0f4f6] text-[#0d8f88]"><Stethoscope size={20} /></span></div><div className="mt-7 flex items-center gap-3 border-t border-[#edf2f4] pt-5 text-sm text-[#526675]"><CalendarDays size={16} className="text-[#0d8f88]" /> Thursday, 24 October <span className="text-[#b0bbc2]">·</span> 10:30 AM</div><button className="mt-5 flex items-center gap-1 text-sm font-bold text-[#0d8f88]">View details <ChevronRight size={15} /></button></PortalCard>
    </div>
    <div className="mt-12 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#0d8f88]">Your health journey</p><h2 className="mt-2 font-serif text-2xl font-bold">Recent check-ins</h2></div><Link href="/patient/intake" className="hidden items-center gap-2 text-sm font-bold text-[#0d8f88] sm:flex"><Plus size={16} /> New check-in</Link></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><PortalCard className="p-6"><div className="flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-[#eef7f6] text-[#0d8f88]"><FileText size={18} /></span><span className="text-xs font-semibold text-[#8a9aa5]">18 Oct 2024</span></div><h3 className="mt-5 font-serif text-xl font-bold">Headache &amp; fatigue</h3><p className="mt-2 text-sm leading-6 text-[#718391]">Your report is ready to review.</p><Link href="/patient/report" className="mt-5 flex items-center gap-2 text-sm font-bold text-[#0d8f88]">Open report <ArrowRight size={15} /></Link></PortalCard><PortalCard className="p-6"><div className="flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-[#f1f4f5] text-[#718391]"><Clock3 size={18} /></span><span className="text-xs font-semibold text-[#8a9aa5]">02 Oct 2024</span></div><h3 className="mt-5 font-serif text-xl font-bold">Seasonal allergies</h3><p className="mt-2 text-sm leading-6 text-[#718391]">Discussed with Dr. Shah.</p><button className="mt-5 flex items-center gap-2 text-sm font-bold text-[#718391]">View details <ChevronRight size={15} /></button></PortalCard></div>
  </PageContainer></PatientShell>
}
