"use client"

import { useState } from "react"
import { Check, ChevronRight, Globe2, KeyRound, LockKeyhole, Mail, Moon, Save, ShieldCheck, Smartphone, UserRound } from "lucide-react"
import { DoctorPage } from "@/components/doctor-portal"

export default function DoctorSettings() {
  const [saved, setSaved] = useState(false)
  const [emailAlerts, setEmailAlerts] = useState(true)
  const [criticalAlerts, setCriticalAlerts] = useState(true)
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2400) }
  return <DoctorPage><div className="flex flex-col gap-8">
    <div><p className="text-sm font-semibold text-[#0d8f88]">Workspace preferences</p><h1 className="mt-2 font-serif text-3xl font-bold tracking-tight text-[#1d3445] md:text-4xl">Settings</h1><p className="mt-2 text-[#718391]">Manage your clinician profile, notifications, and security.</p></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_330px]">
      <div className="flex flex-col gap-6"><section className="rounded-2xl border border-[#e5edf0] bg-white p-6 shadow-sm"><SectionTitle icon={UserRound} title="Professional profile" description="This information appears on your patient communications." /><div className="mt-6 flex flex-col gap-5"><div className="flex items-center gap-4"><span className="flex size-16 items-center justify-center rounded-2xl bg-[#dceeed] font-serif text-xl font-bold text-[#0d7771]">DP</span><div><p className="font-bold">Dr. Priya Patel</p><p className="text-sm text-[#718391]">Profile photo · JPG or PNG up to 5MB</p></div><button className="ml-auto rounded-lg border border-[#dce7ea] px-3 py-2 text-xs font-bold text-[#0d7771]">Change</button></div><div className="grid gap-5 md:grid-cols-2"><Field label="Full name" value="Dr. Priya Patel" /><Field label="Specialty" value="General Physician" /><Field label="Registration number" value="GJ-MED-2014-0847" /><Field label="Clinic / organization" value="VaaniDoc Care Network" /></div></div></section>
      <section className="rounded-2xl border border-[#e5edf0] bg-white p-6 shadow-sm"><SectionTitle icon={Globe2} title="Preferences" description="Personalize your clinical workspace." /><div className="mt-6 flex flex-col gap-1"><Preference label="Language" value="English (India)" /><Preference label="Time zone" value="Asia/Kolkata (GMT+5:30)" /><Preference label="Appearance" value="Light" icon={Moon} /></div></section>
      <section className="rounded-2xl border border-[#e5edf0] bg-white p-6 shadow-sm"><SectionTitle icon={Mail} title="Notifications" description="Choose how VaaniDoc keeps you informed." /><div className="mt-6 flex flex-col gap-5"><Toggle label="Critical patient alerts" description="Urgent risk signals and time-sensitive care updates." checked={criticalAlerts} onChange={() => setCriticalAlerts(!criticalAlerts)} /><Toggle label="Email summaries" description="A daily digest of your patient activity and reports." checked={emailAlerts} onChange={() => setEmailAlerts(!emailAlerts)} /></div></section><button onClick={save} className="flex w-fit items-center gap-2 rounded-xl bg-[#0d8f88] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#0d8f88]/15 transition hover:bg-[#0b7c76]">{saved ? <Check size={17} /> : <Save size={17} />} {saved ? "Changes saved" : "Save changes"}</button></div>
      <aside className="flex flex-col gap-6"><section className="rounded-2xl border border-[#e5edf0] bg-white p-6 shadow-sm"><SectionTitle icon={ShieldCheck} title="Security & privacy" description="Your account is protected." /><div className="mt-5 flex flex-col gap-3"><StatusRow icon={LockKeyhole} label="Password" value="Last changed 34 days ago" /><StatusRow icon={Smartphone} label="Two-factor authentication" value="Not enabled" warning /><StatusRow icon={KeyRound} label="Active sessions" value="1 current session" /></div></section><section className="rounded-2xl border border-[#e5edf0] bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#0d8f88]">System status</p><h2 className="mt-3 font-serif text-xl font-bold">All systems healthy</h2><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#edf9f4] p-3"><span className="size-2.5 rounded-full bg-[#35a37f]" /><span className="text-sm font-semibold text-[#28775d]">AI processing operational</span></div><p className="mt-4 text-xs text-[#91a1aa]">VaaniDoc v2.8.1 · Last checked just now</p></section><section className="rounded-2xl bg-[#12304a] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8ee0d7]">About VaaniDoc</p><h2 className="mt-3 font-serif text-xl font-bold">Care, understood.</h2><p className="mt-2 text-sm leading-6 text-[#c9dce5]">Helping clinicians spend less time translating and more time listening.</p><button className="mt-4 flex items-center gap-1 text-sm font-bold text-[#8ee0d7]">Visit help center <ChevronRight size={15} /></button></section></aside>
    </div></div></DoctorPage>
}
function SectionTitle({ icon: Icon, title, description }: { icon: typeof UserRound; title: string; description: string }) { return <div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#eaf6f5] text-[#0d8f88]"><Icon size={18} /></span><div><h2 className="font-serif text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-[#718391]">{description}</p></div></div> }
function Field({ label, value }: { label: string; value: string }) { return <label className="flex flex-col gap-2"><span className="text-xs font-bold text-[#718391]">{label}</span><input defaultValue={value} className="rounded-xl border border-[#dce7ea] bg-[#fbfdfd] px-3.5 py-3 text-sm font-semibold text-[#1d3445] outline-none transition focus:border-[#0d8f88] focus:ring-2 focus:ring-[#0d8f88]/10" /></label> }
function Preference({ label, value, icon: Icon = Globe2 }: { label: string; value: string; icon?: typeof Globe2 }) { return <button className="flex items-center gap-3 border-b border-[#edf2f4] py-4 text-left last:border-0"><Icon size={17} className="text-[#0d8f88]" /><span className="flex-1"><span className="block text-xs text-[#91a1aa]">{label}</span><span className="mt-1 block text-sm font-bold">{value}</span></span><ChevronRight size={16} className="text-[#9aaab3]" /></button> }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold">{label}</p><p className="mt-1 text-xs leading-5 text-[#718391]">{description}</p></div><button role="switch" aria-checked={checked} onClick={onChange} className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked ? "bg-[#0d8f88]" : "bg-[#cbd8dd]"}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow-sm transition ${checked ? "left-6" : "left-1"}`} /></button></div> }
function StatusRow({ icon: Icon, label, value, warning }: { icon: typeof LockKeyhole; label: string; value: string; warning?: boolean }) { return <div className="flex items-center gap-3 rounded-xl bg-[#f8fbfc] p-3"><span className="flex size-9 items-center justify-center rounded-lg bg-white text-[#0d8f88] shadow-sm"><Icon size={16} /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{label}</p><p className={`mt-1 text-xs ${warning ? "text-[#d86150]" : "text-[#718391]"}`}>{value}</p></div><ChevronRight size={15} className="text-[#9aaab3]" /></div> }
